'use strict';

/**
 * The real Liquid Sky menu — 287 lines across 13 sections, transcribed
 * from the restaurant's own card and verified against the prices used on
 * the public site.
 *
 * Two fields here are OURS, not the restaurant's, and the kitchen is the
 * authority on both:
 *
 *   station       which counter the ticket prints at. Derived from the
 *                 section, then from the dish name — a "Paneer Tikka" in
 *                 Starters still belongs at the tandoor, not the curry
 *                 range. Correct them in /admin.
 *   prep_minutes  an estimate per station, used by the "ready soon"
 *                 filter on the kitchen screens.
 *
 * Unlike the multi-cuisine template this was ported from, Liquid Sky has
 * a bar: 62 of the 287 lines are mocktails, cocktails and spirits, and
 * they route to BAR so a bartender is not staring at a curry ticket.
 *
 * A price of 0 means the card says "ask" — market price, confirmed at the
 * table.
 */

const CATEGORIES = [
  { key: 'starters', name: 'Starters', name_hi: 'स्टार्टर', name_kn: 'ಸ್ಟಾರ್ಟರ್', sort_order: 1 },
  { key: 'tandoor', name: 'Tandoor', name_hi: 'तंदूर', name_kn: 'ತಂದೂರಿ', sort_order: 2 },
  { key: 'soups', name: 'Soups', name_hi: 'सूप', name_kn: 'ಸೂಪ್', sort_order: 3 },
  { key: 'mains', name: 'Mains', name_hi: 'मुख्य व्यंजन', name_kn: 'ಮುಖ್ಯ ಖಾದ್ಯ', sort_order: 4 },
  { key: 'biryani', name: 'Biryani', name_hi: 'बिरयानी', name_kn: 'ಬಿರಿಯಾನಿ', sort_order: 5 },
  { key: 'chinese', name: 'Chinese', name_hi: 'चाइनीज़', name_kn: 'ಚೈನೀಸ್', sort_order: 6 },
  { key: 'coastal', name: 'Coastal', name_hi: 'तटीय', name_kn: 'ಕರಾವಳಿ', sort_order: 7 },
  { key: 'breads', name: 'Breads', name_hi: 'रोटी', name_kn: 'ರೊಟ್ಟಿ', sort_order: 8 },
  { key: 'sides', name: 'Sides', name_hi: 'साइड्स', name_kn: 'ಸೈಡ್ಸ್', sort_order: 9 },
  { key: 'desserts', name: 'Desserts', name_hi: 'मिठाई', name_kn: 'ಸಿಹಿ', sort_order: 10 },
  { key: 'mocktails', name: 'Mocktails', name_hi: 'मॉकटेल', name_kn: 'ಮಾಕ್‌ಟೈಲ್', sort_order: 11 },
  { key: 'cocktails', name: 'Cocktails', name_hi: 'कॉकटेल', name_kn: 'ಕಾಕ್‌ಟೈಲ್', sort_order: 12 },
  { key: 'spirits', name: 'Spirits', name_hi: 'स्पिरिट्स', name_kn: 'ಸ್ಪಿರಿಟ್ಸ್', sort_order: 13 },
];

const ITEMS = [
  ['starters', 'Masala Papad', '', 75, 'VEG', 'CURRY', 15, 2, 0],
  ['starters', 'Peanut Masala', '', 180, 'VEG', 'CURRY', 15, 2, 0],
  ['starters', 'French Fry', '', 180, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Onion Pakora', '', 199, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Onion Rings', '', 199, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Papad Roasted / Fry', '', 60, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Mix Veg Pakora', '', 210, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Cheese Ball', '', 275, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Corn Cheese Ball', '', 295, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Potato Cheese Ball', '', 260, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Cashew Fry', '', 260, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Veg Ball Manchurian', '', 225, 'VEG', 'CHINESE', 12, 1, 0],
  ['starters', 'Gobi — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 210, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Baby Corn — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 240, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Mushroom — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 240, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Paneer — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 270, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Chilly Potato', '', 210, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Honey Chilly Potato', '', 230, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Honey Chilly Cauliflower', '', 230, 'VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Stuffed Mushroom (hot garlic sauce)', '', 280, 'VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Egg — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 205, 'EGG', 'CHINESE', 12, 2, 0],
  ['starters', 'Chicken — Manchurian / Chilly / 65 / Pepper / Salt & Pepper', '', 319, 'NON_VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Crispy Chicken', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Lemon Chicken', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Hongkong Chicken', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Dice Chicken Basin / Sauce', '', 340, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Szechwan Chicken', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Kung Pao Chicken', '', 330, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Honey Chilly Chicken', '', 330, 'NON_VEG', 'CHINESE', 12, 2, 1],
  ['starters', 'Dragon Chicken', '', 330, 'NON_VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Chicken Satay', '', 340, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Chicken Lollypop', '', 340, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Drums of Heaven', '', 369, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Chicken Fry', '', 329, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Chicken Pepper Fry', '', 329, 'NON_VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Chicken Kabab', '', 329, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['starters', 'Guntur Chicken', '', 329, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['starters', 'Mutton Fry', '', 410, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Mutton Pepper Fry', '', 430, 'NON_VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Prawns Fry', '', 0, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['starters', 'Prawns Pepper Fry', '', 0, 'NON_VEG', 'CHINESE', 12, 2, 0],
  ['starters', 'Boiled Egg', '', 70, 'EGG', 'CURRY', 15, 1, 0],
  ['starters', 'Egg Omelet', '', 80, 'EGG', 'CURRY', 15, 1, 0],
  ['starters', 'Egg Burji', '', 99, 'EGG', 'CURRY', 15, 1, 0],
  ['starters', 'Masala Omelet', '', 99, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['starters', 'Cheese Omelet', '', 145, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['tandoor', 'Paneer Tikka', '', 299, 'VEG', 'TANDOOR', 18, 1, 1],
  ['tandoor', 'Paneer Malai Tikka', '', 310, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Paneer Hariyali Tikka', '', 299, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Paneer Achari Tikka', '', 299, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Tandoori Mushroom', '', 275, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Mushroom Hariyali Tikka', '', 275, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Baby Corn Tandoori', '', 290, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Gobi Tandoori', '', 230, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Tandoori Aloo Dopiaza', '', 230, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Aloo Sholay', '', 230, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Veg Seekh Kabab', '', 280, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Matai Seekh Kabab', '', 290, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Hara Bhara Kabab', '', 299, 'VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Chicken Tikka', '', 319, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Chicken Malai Tikka', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Angara Tikka', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Achari Tikka', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Chicken Pahadi Kabab', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Banjara Kabab', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Chicken Sholay Kabab', '', 350, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Kalmi Kabab', '', 380, 'NON_VEG', 'TANDOOR', 18, 1, 1],
  ['tandoor', 'Murgh Lasooni Kabab', '', 349, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Irani Tikka', '', 349, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Afghani Tikka', '', 349, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Murgh Kalimirch Tikka', '', 349, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['tandoor', 'Tandoori Chicken', '', 530, 'NON_VEG', 'TANDOOR', 18, 1, 0],
  ['soups', 'Tomato Soup', '', 110, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Sweet Corn Veg Soup', '', 125, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Veg Manchow Soup', '', 125, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Veg Hot & Sour Soup', '', 125, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Lemon Coriander Soup', '', 120, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Burnt Garlic Soup', '', 125, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Veg Clear Soup', '', 110, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Veg Talumein Soup', '', 125, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Mushroom Clear Soup', '', 120, 'VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Clear Soup', '', 140, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Sweet Corn Soup', '', 140, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Manchow Soup', '', 150, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Hot & Sour Soup', '', 150, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Lemon Coriander Soup', '', 140, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Burnt Garlic Soup', '', 150, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Talumein Soup', '', 155, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['soups', 'Tomato Egg Drop Soup', '', 140, 'EGG', 'CHINESE', 12, 1, 0],
  ['soups', 'Chicken Lung Fung Soup', '', 150, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['mains', 'Dal Fry', '', 175, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Dal Tadka', '', 195, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Dal Palak', '', 190, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Dal Methi', '', 195, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Dal Punjabi', '', 195, 'VEG', 'CURRY', 15, 1, 1],
  ['mains', 'Mix Veg Curry', '', 245, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Veg Dopiaza', '', 245, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Veg Kolhapuri', '', 245, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Veg Hyderabadi', '', 245, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Veg Kadai', '', 250, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Paneer Butter Masala', '', 285, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Paneer Kolhapuri', '', 285, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Paneer Kadai', '', 285, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Paneer Hyderabadi', '', 285, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Palak Paneer', '', 285, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Paneer Saagwala', '', 285, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Paneer Tikka Masala', '', 299, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Paneer Mutter Masala', '', 285, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Mushroom Kadai', '', 245, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mushroom Dopiaza', '', 245, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mushroom Mutter Masala', '', 245, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Methi Mutter Malai', '', 269, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Veg Kofta Curry', '', 265, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Malai Kofta', '', 299, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Aloo Jeera Dry', '', 190, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Aloo Methi Dry', '', 210, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Aloo Palak', '', 220, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Aloo Mutter', '', 220, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Aloo Gobi', '', 220, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Kaju Masala', '', 310, 'VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Kaju Kadai', '', 319, 'VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Masala', '', 299, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Chicken Dopiaza', '', 310, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Kolhapuri', '', 310, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Chicken Kadai', '', 310, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Mughlai', '', 349, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Handi', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Butter Chicken', '', 349, 'NON_VEG', 'CURRY', 15, 1, 1],
  ['mains', 'Ginger Chicken Masala', '', 319, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Chicken Hyderabadi', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Saagwala', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Murgh Methi', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Tikka Masala', '', 349, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Chicken Patiala', '', 360, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Punjabi', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Kalmi Masala', '', 319, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Chicken Kali Mirch', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Chicken Bharta', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mutton Masala', '', 410, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Mutton Dopiaza', '', 410, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mutton Kolhapuri', '', 410, 'NON_VEG', 'CURRY', 15, 2, 0],
  ['mains', 'Mutton Kadai', '', 410, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mutton Handi', '', 419, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['mains', 'Mutton Rogan Josh', '', 419, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['biryani', 'Egg Biriyani', '', 230, 'EGG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Chicken Dum Biriyani', '', 310, 'NON_VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Chicken Tikka Biriyani', '', 349, 'NON_VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Tandoori Chicken Biriyani', '', 349, 'NON_VEG', 'BIRYANI', 22, 1, 1],
  ['biryani', 'Chicken Kalmi Biriyani', '', 349, 'NON_VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Fish Tikka Biriyani', '', 375, 'NON_VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Mutton Biriyani', '', 410, 'NON_VEG', 'BIRYANI', 22, 1, 1],
  ['biryani', 'Plain Rice', '', 90, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Steamed Rice (Basmati)', '', 130, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Ghee Rice', '', 195, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Jeera Rice', '', 175, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Veg Pulao', '', 220, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Peas Pulao', '', 210, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Veg Biriyani', '', 219, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Mushroom Biriyani', '', 219, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Paneer Biriyani', '', 229, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Dal Khichdi', '', 195, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Dal Palak Khichdi', '', 210, 'VEG', 'BIRYANI', 22, 1, 0],
  ['biryani', 'Palak Rice', '', 219, 'VEG', 'BIRYANI', 22, 1, 0],
  ['chinese', 'Veg Fried Rice', '', 230, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Mushroom Fried Rice', '', 240, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chilly Garlic Fried Rice', '', 249, 'VEG', 'CHINESE', 12, 2, 0],
  ['chinese', 'Paneer Fried Rice', '', 265, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Burnt Garlic Fried Rice', '', 249, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Veg Triple Szechwan Fried Rice', '', 260, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Veg Mix Fried Rice', '', 250, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Veg Noodles', '', 230, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Mushroom Noodles', '', 240, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chilly Garlic Noodles', '', 240, 'VEG', 'CHINESE', 12, 2, 1],
  ['chinese', 'Paneer Noodles', '', 270, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Burnt Garlic Noodles', '', 250, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Veg Mix Noodles', '', 265, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Singapore Noodles', '', 265, 'VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Egg Fried Rice', '', 230, 'EGG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Corn Egg Fried Rice', '', 240, 'EGG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chilly Garlic Egg Fried Rice', '', 250, 'EGG', 'CHINESE', 12, 2, 0],
  ['chinese', 'Burnt Garlic Egg Fried Rice', '', 250, 'EGG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chicken Fried Rice', '', 285, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Prawn Fried Rice', '', 340, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Non-Veg Mix Fried Rice', '', 369, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Non-Veg Triple Szechwan Fried Rice', '', 350, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Egg Noodles', '', 230, 'EGG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chicken Noodles', '', 285, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Non-Veg Singapore Noodles', '', 310, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chicken Burnt Garlic Noodles', '', 285, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Chicken Garlic Noodles', '', 285, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['chinese', 'Non-Veg Mix Noodles', '', 369, 'NON_VEG', 'CHINESE', 12, 1, 0],
  ['coastal', 'Chicken Sukka', '', 329, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['coastal', 'Chicken Koliwada', '', 319, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['coastal', 'Fish Curry', '', 180, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['coastal', 'Fish Koliwada', '', 339, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['coastal', 'Fish Curry Rice', '', 240, 'NON_VEG', 'CURRY', 15, 1, 0],
  ['coastal', 'Boiled Rice', '', 100, 'VEG', 'CURRY', 15, 1, 0],
  ['breads', 'Tandoori Roti', '', 45, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Naan', '', 55, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Garlic Naan', '', 65, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Lachha Paratha', '', 55, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Methi Paratha', '', 55, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Pudhina Paratha', '', 55, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Cheese Naan', '', 80, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Cheese Garlic Naan', '', 90, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Kulcha', '', 55, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Stuff Kulcha', '', 80, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Aloo Kulcha', '', 70, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Aloo Paratha', '', 105, 'VEG', 'TANDOOR', 18, 0, 0],
  ['breads', 'Paneer Paratha', '', 120, 'VEG', 'TANDOOR', 18, 0, 0],
  ['sides', 'Green Salad', '', 160, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Cucumber Salad', '', 145, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Onion Salad', '', 135, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Corn Salad', '', 190, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Fruit Salad', '', 210, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Plain Curd', '', 60, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Mix Raita', '', 85, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Cucumber Raita', '', 85, 'VEG', 'CURRY', 15, 1, 0],
  ['sides', 'Boondi Raita', '', 95, 'VEG', 'CURRY', 15, 1, 0],
  ['desserts', 'Gulab Jamun', '', 95, 'VEG', 'DESSERT', 6, 0, 1],
  ['desserts', 'Gajar Halwa', '', 110, 'VEG', 'DESSERT', 6, 0, 0],
  ['desserts', 'Vanilla Ice Cream', '', 100, 'VEG', 'DESSERT', 6, 0, 0],
  ['desserts', 'Strawberry Ice Cream', '', 100, 'VEG', 'DESSERT', 6, 0, 0],
  ['desserts', 'Chocolate Ice Cream', '', 110, 'VEG', 'DESSERT', 6, 0, 0],
  ['desserts', 'Butterscotch Ice Cream', '', 120, 'VEG', 'DESSERT', 6, 0, 0],
  ['mocktails', 'Fresh Fruit Juice', '', 160, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Fresh Lime Juice', '', 70, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Fresh Lime Soda', '', 95, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Virgin Mojito', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Virgin Mary', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Fruit Punch', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Blue Sky', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['mocktails', 'Virgin Water Melon Mojito', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Bull Frog', '', 620, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Long Island Ice Tea', '', 620, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Jager Bomb', '', 600, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Screw Driver', '', 340, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Mojito', '', 340, 'VEG', 'BAR', 4, 0, 1],
  ['cocktails', 'Cosmopolitan', '', 340, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Bloody Mary', '', 340, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Whiskey Sour', '', 340, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Breezer (275 ml)', '', 225, 'VEG', 'BAR', 4, 0, 0],
  ['cocktails', 'Bacardi Plus (275 ml)', '', 195, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Chivas Regal', '', 400, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Black Label', '', 400, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Jack Daniels', '', 380, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Red Label', '', 270, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Teacher\'s 50', '', 270, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Jim Beam', '', 220, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Black Dog', '', 180, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Black & White', '', 180, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Teacher\'s Highland', '', 180, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', '100 Pipers', '', 180, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Vat 69', '', 180, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Antiquity Blue', '', 150, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Blenders Pride', '', 145, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Signature Rare', '', 140, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Royal Challenge', '', 105, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Royal Stag', '', 105, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Imperial Blue', '', 75, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'MC No.1', '', 75, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Morpheus Brandy', '', 140, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Courrier Napoleon Brandy', '', 100, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Mansion House Brandy', '', 75, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Bacardi Regular', '', 145, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Bacardi Flavors', '', 145, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Old Monk', '', 55, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Smirnoff Flavors', '', 140, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Smirnoff Plain', '', 140, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Romanov Plain', '', 75, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Gig Nagpur Orange Gin', '', 125, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Gig Regular Gin', '', 120, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Blue Riband Gin', '', 70, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Jagermeister', '', 440, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Desmondji', '', 260, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Cellier Rose Wine', '', 125, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Sula Red Wine', '', 65, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Sula White Wine', '', 60, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Carlsberg Elephant', '', 410, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Carlsberg Smooth', '', 400, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Budweiser Magnum', '', 405, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Budweiser', '', 380, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Kingfisher Strong', '', 325, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Kingfisher Premium', '', 320, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Tuborg Strong', '', 325, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Tuborg Green', '', 320, 'VEG', 'BAR', 4, 0, 0],
  ['spirits', 'Corona', '', 350, 'VEG', 'BAR', 4, 0, 0],
];

module.exports = { CATEGORIES, ITEMS };
